"""update user 3

Revision ID: 045fe222194b
Revises: 371051fbb541
Create Date: 2023-11-02 15:52:31.318879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '045fe222194b'
down_revision = '371051fbb541'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_user', 'admin', 'default_user', name='role'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_user', 'admin', 'default_user', name='role'),
               nullable=False)
    # ### end Alembic commands ###
