"""update user 2

Revision ID: 06eb687bff12
Revises: 42b0d300a8a5
Create Date: 2023-11-01 20:13:26.681396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06eb687bff12'
down_revision = '42b0d300a8a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
