"""update user 3

Revision ID: 0e20412940c6
Revises: 06eb687bff12
Create Date: 2023-11-01 20:14:31.919692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e20412940c6'
down_revision = '06eb687bff12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
