"""init

Revision ID: 263810a0a85d
Revises: 
Create Date: 2023-10-31 15:37:20.861240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263810a0a85d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
