"""update user

Revision ID: 2cfd9b5e7945
Revises: 7644a1096444
Create Date: 2023-11-26 21:06:24.460661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfd9b5e7945'
down_revision = '7644a1096444'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
