"""update user 2

Revision ID: 371051fbb541
Revises: 4bbd1426427e
Create Date: 2023-11-02 15:50:43.738009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371051fbb541'
down_revision = '4bbd1426427e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
