"""update user

Revision ID: 42b0d300a8a5
Revises: 723539bf1d4e
Create Date: 2023-11-01 12:26:02.388132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b0d300a8a5'
down_revision = '723539bf1d4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
