"""update user

Revision ID: 4bbd1426427e
Revises: cd729cc6a329
Create Date: 2023-11-02 15:47:58.751972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbd1426427e'
down_revision = 'cd729cc6a329'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
