"""update model user 2

Revision ID: 5bfb7e4cacea
Revises: cda7cf41a3a2
Create Date: 2023-10-31 18:55:28.787156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bfb7e4cacea'
down_revision = 'cda7cf41a3a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
