"""update model user 6

Revision ID: 723539bf1d4e
Revises: c0a117d2ae1e
Create Date: 2023-10-31 19:03:05.479937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723539bf1d4e'
down_revision = 'c0a117d2ae1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
