"""update user role

Revision ID: 731f80dd5609
Revises: 2cfd9b5e7945
Create Date: 2023-11-29 15:56:09.803101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731f80dd5609'
down_revision = '2cfd9b5e7945'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
