"""update model user 3

Revision ID: 9b88c649e44a
Revises: 5bfb7e4cacea
Create Date: 2023-10-31 18:58:12.194288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b88c649e44a'
down_revision = '5bfb7e4cacea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
