"""update model user 4

Revision ID: a901bd95bbda
Revises: 9b88c649e44a
Create Date: 2023-10-31 19:00:43.260717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a901bd95bbda'
down_revision = '9b88c649e44a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
