"""update model user 5

Revision ID: aa5337333277
Revises: a901bd95bbda
Create Date: 2023-10-31 19:01:28.520530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5337333277'
down_revision = 'a901bd95bbda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
