"""update model user 5

Revision ID: c0a117d2ae1e
Revises: aa5337333277
Create Date: 2023-10-31 19:02:12.788764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a117d2ae1e'
down_revision = 'aa5337333277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
