"""update model user

Revision ID: cda7cf41a3a2
Revises: 0a36d1faa95c
Create Date: 2023-10-31 18:11:23.185348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda7cf41a3a2'
down_revision = '0a36d1faa95c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
