"""update user 4

Revision ID: cf1220495169
Revises: 045fe222194b
Create Date: 2023-11-02 15:54:48.713960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf1220495169'
down_revision = '045fe222194b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('super_user', 'admin', 'default_user', name='role'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
