"""update user 4

Revision ID: d9e69816d7d2
Revises: 0e20412940c6
Create Date: 2023-11-01 20:26:25.716708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e69816d7d2'
down_revision = '0e20412940c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
